version: '3.4'

services:
  oddsdb:
    image: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  odds.api:
    image: ${DOCKER_REGISTRY-}oddsapi
    build:
      context: .
      dockerfile: Services/Odds.API/Dockerfile

  Odds.Client:
    image: ${DOCKER_REGISTRY-}ods.client
    build: 
      context: .
      dockerfile: Client/Odds.Client




volumes:
  oddsdb_data:
  pgadmin_data:
  postgres_data:
