version: '3.4'

services:
  oddsdb:
    image: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  odds.api:
    image: ${DOCKER_REGISTRY-}oddsapi
    build:
      context: .
      dockerfile: Services/Odds.API/Dockerfile

  odds.client:
    image: ${DOCKER_REGISTRY-}odds.client
    build: 
      context: .
      dockerfile: Odds.Client/Odds.Client/Dockerfile




volumes:
  oddsdb_data:
  pgadmin_data:
  postgres_data:
