version: '3.4'

services:
  oddsdb:
    container_name: oddsdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=OddsDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@oddesodd.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  odds.api:
    container_name: odds.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OddsConnectionString=Server=oddsdb;Port=5432;Database=OddsDb;User Id=admin;Password=admin1234;"
    depends_on:
      - oddsdb
    ports:
      - "8000:80"
