version: '3.4'

services:
  oddsdb:
    container_name: oddsdb
    hostname: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=OddsDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=admin@odds.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - oddsdb
    volumes:
      - pgadmin_data:/root/.pgadmin

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15670:5672"
      - "15672:15672"

  odds.api:
    container_name: odds.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OddsConnectionString=Server=oddsdb;Port=5432;Database=OddsDb;User Id=admin;Password=admin1234;"
      - "RabbitMq:Hostname=rabbitmq"
      - "RabbitMq:QueueName=SelectionQueue"
      - "RabbitMq:UserName=guest"
      - "RabbitMq:Password=guest"
      - "RabbitMq:Port=5672"
    depends_on:
      - oddsdb
      - rabbitmq
    ports:
      - "8000:80"

  odds.client:
    container_name: odds.client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RabbitMq:Hostname=rabbitmq"
      - "RabbitMq:QueueName=SelectionQueue"
      - "RabbitMq:UserName=guest"
      - "RabbitMq:Password=guest"
      - "RabbitMq:Port=5672"
      - "ApiSettings:GatewayAddress=http://odds.api"
    depends_on:
      - oddsdb
      - rabbitmq
      - odds.api
    ports:
      - "8001:80"
